before_script:
  - export PATH=/usr/lib/ccache:$PATH
  - touch .gitlab-runner
  - git config --global user.email "$GITLAB_USER_EMAIL"
  - git config --global user.name "$GITLAB_USER_NAME"
  - git config --global advice.detachedHead false

build-v6.6-debian-13-riscv64:
  image: robertcnelson/beagle-devscripts-kernel-debian-12-amd64:latest
  # https://openbeagle.org/beagleboard/ci-docker-images
  cache:
    key: "$CI_PROJECT_NAME-v6.6-debian-13-riscv64"
    paths:
      - mirror/x86_64-gcc-*-linux.tar.xz
      - ccache.tar.lz4
  tags:
    - docker-amd64
  stage: build
  script:
    - ./01_git_sync.sh
    - ./02_build_hss.sh
    - ./03_build_u-boot.sh
    - mkdir -p /root/.cache/ccache/ || true
    - tar --use-compress-program=lz4 -xf ccache.tar.lz4 -C / || true
    - ccache -M 1G
    - ccache -z
    - ./04_build_linux.sh
    - ccache -sv
    - tar --use-compress-program=lz4 -cf ccache.tar.lz4 /root/.cache/ccache/
    - du -sh ccache.tar.lz4
    - ./05_generate_payload.bin.sh
    - ./06_generate_debian_console_root.sh
    - ./07_create_sdcard_img.sh
    - xz -vT8 deploy/images/sdcard.img
    - tree -s deploy/
    - cp -v deploy/images/sdcard.img.xz ./deploy/
    - cp -v deploy/images/sdcard.bmap ./deploy/
  artifacts:
    when: on_success
    expire_in: 4 week
    name: "$CI_PROJECT_NAME-v6.6-debian-13-riscv64-$CI_JOB_ID"
    paths:
      - "deploy/sdcard.img.xz"
      - "deploy/sdcard.bmap"
      - "deploy/readme.md"

build-v6.6-ubuntu-2404-riscv64:
  image: robertcnelson/beagle-devscripts-kernel-debian-12-amd64:latest
  # https://openbeagle.org/beagleboard/ci-docker-images
  cache:
    key: "$CI_PROJECT_NAME-v6.6-ubuntu-2404-riscv64"
    paths:
      - mirror/x86_64-gcc-*-linux.tar.xz
      - ccache.tar.lz4
  tags:
    - docker-amd64
  stage: build
  script:
    - ./01_git_sync.sh
    - ./02_build_hss.sh
    - ./03_build_u-boot.sh
    - mkdir -p /root/.cache/ccache/ || true
    - tar --use-compress-program=lz4 -xf ccache.tar.lz4 -C / || true
    - ccache -M 1G
    - ccache -z
    - ./04_build_linux.sh
    - ccache -sv
    - tar --use-compress-program=lz4 -cf ccache.tar.lz4 /root/.cache/ccache/
    - du -sh ccache.tar.lz4
    - ./05_generate_payload.bin.sh
    - ./06_generate_ubuntu_console_root.sh
    - ./07_create_sdcard_img.sh
    - xz -vT8 deploy/images/sdcard.img
    - tree -s deploy/
    - cp -v deploy/images/sdcard.img.xz ./deploy/
    - cp -v deploy/images/sdcard.bmap ./deploy/
  artifacts:
    when: on_success
    expire_in: 4 week
    name: "$CI_PROJECT_NAME-v6.6-ubuntu-2404-riscv64-$CI_JOB_ID"
    paths:
      - "deploy/sdcard.img.xz"
      - "deploy/sdcard.bmap"
      - "deploy/readme.md"
